connections = {
    112: {'s': 141, 'e': 140, 'w': 100}, 
    141: {'n': 112, 'e': 156}, 140: {'w': 112}, 
    100: {'e': 112, 's': 106, 'w': 68}, 
    106: {'n': 100, 's': 111, 'w': 135}, 
    68: {'e': 100, 'n': 52}, 
    111: {'n': 106, 's': 367, 'e': 158}, 
    135: {'e': 106, 's': 150}, 
    150: {'n': 135, 'w': 166}, 
    166: {'e': 150, 's': 198, 'w': 117}, 
    198: {'n': 166, 's': 239, 'e': 199}, 
    117: {'e': 166, 's': 131, 'n': 108, 'w': 133}, 
    367: {'n': 111}, 
    158: {'w': 111, 's': 167}, 
    52: {'s': 68, 'n': 35, 'e': 75}, 
    35: {'s': 52, 'w': 34}, 
    75: {'w': 52, 'e': 85}, 
    85: {'w': 75, 'e': 154}, 
    156: {'w': 141, 's': 168, 'e': 164}, 
    168: {'n': 156, 'e': 340}, 
    164: {'w': 156, 'n': 217, 'e': 298}, 
    217: {'s': 164, 'e': 247}, 
    298: {'w': 164, 's': 324}, 
    247: {'w': 217, 'e': 261}, 
    324: {'n': 298, 's': 349, 'e': 354}, 
    340: {'w': 168}, 
    261: {'w': 247, 's': 277, 'e': 322}, 
    277: {'n': 261, 'e': 323}, 
    322: {'w': 261, 'n': 382, 'e': 435}, 
    382: {'s': 322, 'e': 388}, 
    435: {'w': 322}, 
    388: {'w': 382, 'e': 477}, 
    477: {'w': 388, 'e': 483}, 
    483: {'w': 477}, 
    167: {'n': 158, 's': 262, 'e': 260}, 
    262: {'n': 167, 's': 370, 'e': 358}, 
    260: {'w': 167}, 
    370: {'n': 262, 's': 434, 'e': 407}, 
    358: {'w': 262, 'e': 401}, 
    401: {'w': 358}, 
    434: {'n': 370}, 
    407: {'w': 370, 's': 496}, 
    496: {'n': 407}, 
    154: {'w': 85, 'e': 193}, 
    193: {'w': 154, 'e': 251}, 
    251: {'w': 193, 'e': 315}, 
    315: {'w': 251}, 
    34: {'e': 35, 'n': 14, 's': 50}, 
    14: {'s': 34, 'e': 37, 'w': 12}, 
    50: {'n': 34, 's': 89}, 
    37: {'w': 14}, 
    12: {'e': 14, 'n': 9, 's': 18, 'w': 21}, 
    9: {'s': 12, 'n': 3, 'e': 11}, 
    18: {'n': 12}, 
    21: {'e': 12}, 
    3: {'s': 9, 'e': 5, 'w': 2}, 
    11: {'w': 9}, 
    5: {'w': 3}, 
    2: {'e': 3, 'n': 0, 's': 6}, 
    0: {'s': 2}, 
    6: {'n': 2, 'w': 7}, 
    7: {'e': 6, 'n': 8, 'w': 56}, 
    8: {'s': 7, 'w': 16}, 
    56: {'e': 7}, 
    16: {'e': 8, 'n': 58, 'w': 67}, 
    58: {'s': 16, 'w': 65}, 
    67: {'e': 16, 'w': 162}, 
    162: {'e': 67}, 
    65: {'e': 58, 'n': 74, 'w': 139}, 
    74: {'s': 65, 'n': 87, 'w': 161}, 
    139: {'e': 65, 'w': 188}, 
    188: {'e': 139, 'w': 335}, 
    87: {'s': 74}, 
    161: {'e': 74}, 
    335: {'e': 188, 'w': 366}, 
    366: {'e': 335}, 
    89: {'n': 50, 's': 93}, 
    93: {'n': 89, 'w': 108}, 
    108: {'e': 93, 's': 117, 'n': 78}, 
    239: {'n': 198, 'w': 244}, 
    199: {'w': 198, 's': 230}, 
    230: {'n': 199, 's': 307, 'e': 297}, 
    307: {'n': 230, 's': 373, 'e': 371, 'w': 321}, 
    297: {'w': 230}, 
    373: {'n': 307, 's': 480}, 
    371: {'w': 307, 's': 475}, 
    321: {'e': 307, 's': 413}, 
    475: {'n': 371, 's': 484}, 
    484: {'n': 475}, 
    480: {'n': 373}, 
    413: {'n': 321}, 
    244: {'e': 239, 'n': 131}, 
    131: {'s': 244, 'n': 117, 'w': 138}, 
    138: {'e': 131, 's': 211, 'w': 195}, 
    133: {'e': 117, 'w': 173}, 
    211: {'n': 138}, 
    195: {'e': 138}, 
    78: {'s': 108, 'n': 22}, 
    22: {'s': 78}, 
    323: {'w': 277, 'e': 433}, 
    433: {'w': 323}, 
    349: {'n': 324, 's': 352, 'e': 384, 'w': 356}, 
    354: {'w': 324}, 
    173: {'e': 133, 'w': 214}, 
    214: {'e': 173}, 
    352: {'n': 349, 's': 362, 'e': 485}, 
    384: {'w': 349}, 
    356: {'e': 349}, 
    362: {'n': 352, 's': 399, 'w': 463}, 
    485: {'w': 352}, 
    399: {'n': 362, 's': 467}, 
    463: {'e': 362, 's': 468}, 
    468: {'n': 463}, 
    467: {'n': 399}
    }

rooms = {
    112: {'room_id': 112, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(65,54)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    141: {'room_id': 141, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(65,53)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    140: {'room_id': 140, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(66,54)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['small treasure', 'amazing treasure', 'great treasure'], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    100: {'room_id': 100, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(64,54)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    106: {'room_id': 106, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(64,53)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    68: {'room_id': 68, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(63,54)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    111: {'room_id': 111, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(64,52)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['User 20694'], 'items': [], 'exits': ['n', 's', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    135: {'room_id': 135, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(63,53)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    150: {'room_id': 150, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(63,52)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    166: {'room_id': 166, 'title': 'Mt. Holloway', 'description': 'You are at the base of a large, looming mountain.', 'coordinates': '(62,52)', 'elevation': 1, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['s', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    198: {'room_id': 198, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(62,51)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    117: {'room_id': 117, 'title': 'Mt. Holloway', 'description': 'You are on the side of a steep incline.', 'coordinates': '(61,52)', 'elevation': 2, 'terrain': 'MOUNTAIN', 'players': ['User 20663'], 'items': [], 'exits': ['n', 's', 'e', 'w'], 'cooldown': 20.0, 'errors': [], 'messages': ['You have walked west.', 'Uphill Penalty: 5s CD']}, 
    367: {'room_id': 367, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(64,51)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    158: {'room_id': 158, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(65,52)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    52: {'room_id': 52, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(63,55)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    35: {'room_id': 35, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(63,56)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    75: {'room_id': 75, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(64,55)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    85: {'room_id': 85, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(65,55)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['amazing treasure'], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    156: {'room_id': 156, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(66,53)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    168: {'room_id': 168, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(66,52)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    164: {'room_id': 164, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(67,53)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['raj kamali'], 'items': [], 'exits': ['n', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    217: {'room_id': 217, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(67,54)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    298: {'room_id': 298, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(68,53)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    247: {'room_id': 247, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(68,54)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    324: {'room_id': 324, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(68,52)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['harliquinn'], 'items': [], 'exits': ['n', 's', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    340: {'room_id': 340, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(67,52)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    261: {'room_id': 261, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(69,54)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    277: {'room_id': 277, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(69,53)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    322: {'room_id': 322, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(70,54)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    382: {'room_id': 382, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(70,55)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['emmargherd'], 'items': [], 'exits': ['s', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    435: {'room_id': 435, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(71,54)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['amazing treasure'], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    388: {'room_id': 388, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(71,55)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    477: {'room_id': 477, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(72,55)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    483: {'room_id': 483, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(73,55)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    167: {'room_id': 167, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(65,51)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['josh_fowlkes'], 'items': [], 'exits': ['n', 's', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    262: {'room_id': 262, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(65,50)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['mary'], 'items': ['spectacular treasure'], 'exits': ['n', 's', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    260: {'room_id': 260, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(66,51)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['amazing treasure', 'amazing treasure'], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    370: {'room_id': 370, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(65,49)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    358: {'room_id': 358, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(66,50)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['spectacular treasure', 'shiny treasure', 'great treasure'], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    401: {'room_id': 401, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(67,50)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['great treasure', 'great treasure'], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    434: {'room_id': 434, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(65,48)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    407: {'room_id': 407, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(66,49)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    496: {'room_id': 496, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(66,48)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    154: {'room_id': 154, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(66,55)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    193: {'room_id': 193, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(67,55)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    251: {'room_id': 251, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(68,55)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    315: {'room_id': 315, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(69,55)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    34: {'room_id': 34, 'title': 'Mt. Holloway', 'description': 'You are at the base of a large, looming mountain.', 'coordinates': '(62,56)', 'elevation': 1, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['n', 's', 'e'], 'cooldown': 20.0, 'errors': [], 'messages': ['You have walked north.', 'Uphill Penalty: 5s CD']}, 
    14: {'room_id': 14, 'title': 'Mt. Holloway', 'description': 'You are on the side of a steep incline.', 'coordinates': '(62,57)', 'elevation': 2, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['s', 'e', 'w'], 'cooldown': 20.0, 'errors': [], 'messages': ['You have walked north.', 'Uphill Penalty: 5s CD']}, 
    50: {'room_id': 50, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(62,55)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    37: {'room_id': 37, 'title': 'Mt. Holloway', 'description': 'You are at the base of a large, looming mountain.', 'coordinates': '(63,57)', 'elevation': 1, 'terrain': 'MOUNTAIN', 'players': [], 'items': ['spectacular treasure'], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    12: {'room_id': 12, 'title': 'Mt. Holloway', 'description': 'You are on the side of a steep incline.', 'coordinates': '(61,57)', 'elevation': 3, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['n', 's', 'e', 'w'], 'cooldown': 20.0, 'errors': [], 'messages': ['You have walked west.', 'Uphill Penalty: 5s CD']}, 
    9: {'room_id': 9, 'title': 'Mt. Holloway', 'description': 'You are on the side of a steep incline.', 'coordinates': '(61,58)', 'elevation': 2, 'terrain': 'MOUNTAIN', 'players': ['LindseyCason'], 'items': [], 'exits': ['n', 's', 'e'], 'cooldown': 20.0, 'errors': [], 'messages': ['You have walked south.', 'Uphill Penalty: 5s CD']}, 
    18: {'room_id': 18, 'title': 'Mt. Holloway', 'description': 'You are on the side of a steep incline.', 'coordinates': '(61,56)', 'elevation': 4, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['n', 's', 'w'], 'cooldown': 20.0, 'errors': [], 'messages': ['You have walked south.', 'Uphill Penalty: 5s CD']}, 
    21: {'room_id': 21, 'title': 'Mt. Holloway', 'description': 'You are on the side of a steep incline.', 'coordinates': '(60,57)', 'elevation': 2, 'terrain': 'MOUNTAIN', 'players': [], 'items': ['great treasure'], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    3: {'room_id': 3, 'title': 'Mt. Holloway', 'description': 'You are at the base of a large, looming mountain.', 'coordinates': '(61,59)', 'elevation': 1, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['s', 'e', 'w'], 'cooldown': 20.0, 'errors': [], 'messages': ['You have walked east.', 'Uphill Penalty: 5s CD']}, 
    11: {'room_id': 11, 'title': 'Mt. Holloway', 'description': 'You are at the base of a large, looming mountain.', 'coordinates': '(62,58)', 'elevation': 1, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    5: {'room_id': 5, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(62,59)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    2: {'room_id': 2, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(60,59)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    0: {'room_id': 0, 'title': 'A brightly lit room', 'description': 'You are standing in the center of a brightly lit room. You notice a shop to the west and exits to the north, south and east.', 'coordinates': '(60,60)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['JonathanJAM', 'STRAIGHT DmICK DEMERY', "['BUM']", 'chupacabra', 'Krishan the Quail', 'User 20657', '[Blake-G-CS25]', '[Jon-Solari]', 'User 20725', 'User 20723', 'User 20717', 'User 20711', 'User 20710', 'User 20705', 'User 20692', 'User 20688', 'User 20664'], 'items': [], 'exits': ['n', 's', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    6: {'room_id': 6, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(60,58)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    7: {'room_id': 7, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(59,58)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['am&a'], 'items': [], 'exits': ['n', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    8: {'room_id': 8, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(59,59)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    56: {'room_id': 56, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(58,58)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    16: {'room_id': 16, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(58,59)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    58: {'room_id': 58, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(58,60)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    67: {'room_id': 67, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(57,59)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    162: {'room_id': 162, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(56,59)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    65: {'room_id': 65, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(57,60)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    74: {'room_id': 74, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(57,61)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    139: {'room_id': 139, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(56,60)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    188: {'room_id': 188, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(55,60)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    87: {'room_id': 87, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(57,62)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    161: {'room_id': 161, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(56,61)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    335: {'room_id': 335, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(54,60)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    366: {'room_id': 366, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(53,60)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    89: {'room_id': 89, 'title': 'Mt. Holloway', 'description': 'You are at the base of a large, looming mountain.', 'coordinates': '(62,54)', 'elevation': 1, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['n', 's'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    93: {'room_id': 93, 'title': 'Mt. Holloway', 'description': 'You are on the side of a steep incline.', 'coordinates': '(62,53)', 'elevation': 2, 'terrain': 'MOUNTAIN', 'players': [], 'items': ['spectacular treasure'], 'exits': ['n', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    108: {'room_id': 108, 'title': 'Mt. Holloway', 'description': 'You are on the side of a steep incline.', 'coordinates': '(61,53)', 'elevation': 3, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['n', 's', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    239: {'room_id': 239, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(62,50)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    199: {'room_id': 199, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(63,51)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    230: {'room_id': 230, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(63,50)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    307: {'room_id': 307, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(63,49)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    297: {'room_id': 297, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(64,50)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    373: {'room_id': 373, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(63,48)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['great treasure'], 'exits': ['n', 's'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    371: {'room_id': 371, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(64,49)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['amazing treasure', 'great treasure', 'great treasure'], 'exits': ['s', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    321: {'room_id': 321, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(62,49)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    475: {'room_id': 475, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(64,48)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    484: {'room_id': 484, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(64,47)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['great treasure', 'great treasure'], 'exits': ['n'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    480: {'room_id': 480, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(63,47)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['amazing treasure'], 'exits': ['n'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    413: {'room_id': 413, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(62,48)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['great treasure', 'amazing treasure', 'amazing treasure', 'spectacular treasure', 'amazing treasure', 'shiny treasure', 'amazing treasure'], 'exits': ['n'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    244: {'room_id': 244, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(61,50)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['great treasure'], 'exits': ['n', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    131: {'room_id': 131, 'title': 'Mt. Holloway', 'description': 'You are at the base of a large, looming mountain.', 'coordinates': '(61,51)', 'elevation': 1, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['n', 's', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    138: {'room_id': 138, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(60,51)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    133: {'room_id': 133, 'title': 'Mt. Holloway', 'description': 'You are at the base of a large, looming mountain.', 'coordinates': '(60,52)', 'elevation': 1, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    211: {'room_id': 211, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(60,50)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['great treasure'], 'exits': ['n'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    195: {'room_id': 195, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(59,51)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    78: {'room_id': 78, 'title': 'Mt. Holloway', 'description': 'You are on the side of a steep incline.', 'coordinates': '(61,54)', 'elevation': 4, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['n', 's'], 'cooldown': 20.0, 'errors': [], 'messages': ['You have walked north.', 'Uphill Penalty: 5s CD']}, 
    22: {'room_id': 22, 'title': 'The Peak of Mt. Holloway', 'description': 'You are standing at the zenith of Mt. Holloway. You see before you a holy shrine erected in the image of a magnificent winged deity.', 'coordinates': '(61,55)', 'elevation': 5, 'terrain': 'MOUNTAIN', 'players': [], 'items': [], 'exits': ['n', 's', 'w'], 'cooldown': 20.0, 'errors': [], 'messages': ['You have walked north.', 'Uphill Penalty: 5s CD']}, 
    323: {'room_id': 323, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(70,53)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    433: {'room_id': 433, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(71,53)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['amazing treasure', 'amazing treasure', 'spectacular treasure'], 'exits': ['s', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    349: {'room_id': 349, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(68,51)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    354: {'room_id': 354, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(69,52)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    173: {'room_id': 173, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(59,52)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['e', 'w'], 'cooldown': 7.5, 'errors': [], 'messages': ['You have walked east.', 'Wise Explorer: -50% CD']}, 
    214: {'room_id': 214, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(58,52)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['[Ryan the Quail]'], 'items': [], 'exits': ['n', 'e', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    352: {'room_id': 352, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(68,50)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    384: {'room_id': 384, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(69,51)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['[ HERO ]'], 'items': ['amazing treasure', 'great treasure'], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    356: {'room_id': 356, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(67,51)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['amazing treasure', 'shiny treasure', 'amazing treasure', 'amazing treasure'], 'exits': ['e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    362: {'room_id': 362, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(68,49)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['The Chicken Killer', 'The Great and Knowledgeable Icculus'], 'items': [], 'exits': ['n', 's', 'w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    485: {'room_id': 485, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(69,50)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': ['amazing treasure', 'spectacular treasure', 'great treasure', 'spectacular treasure'], 'exits': ['w'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked east.']}, 
    399: {'room_id': 399, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(68,48)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['n', 's'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked north.']}, 
    463: {'room_id': 463, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(67,49)', 'elevation': 0, 'terrain': 'NORMAL', 'players': [], 'items': [], 'exits': ['s', 'e'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked west.']}, 
    468: {'room_id': 468, 'title': 'A misty room', 'description': 'You are standing on grass and surrounded by a dense mist. You can barely make out the exits in any direction.', 'coordinates': '(67,48)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['daniel'], 'items': ['great treasure'], 'exits': ['n'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}, 
    467: {'room_id': 467, 'title': "Pirate Ry's", 'description': "You see a sign before you that reads:\n\n'You have found Pirate Ry's. Send a `change_name` request and I'll change your identity to whatever you wish... for a price.'", 'coordinates': '(68,47)', 'elevation': 0, 'terrain': 'NORMAL', 'players': ['[TayBic]'], 'items': ['spectacular treasure'], 'exits': ['n'], 'cooldown': 15.0, 'errors': [], 'messages': ['You have walked south.']}
    }

#100x100 grid should leave enough space
grid_row = ["X", " "] * 100 
grid_row_halls = [" "] * 200
grid = []

#generate map (sans room numbers)
for x in range(100):
    grid.append(grid_row)
    grid.append(grid_row_halls)

#draw the map
for i in connections:
    if i in rooms:
        connections[i]["coordinates"] = rooms[i]['coordinates']
        #adjust entries by index, for rooms, which should correspond to coordinates.
        connections[i]["coordinates"] #is a stringified tuple '(68,47)'
        arr = connections[i]["coordinates"].split(",") #split at the comma // ["(68", "47)"]
        X = int(arr[0][1:]) #cast to int after pulling out parens
        Y = int(arr[1][:2])
        #need to account for spaces.
            #every other row is made for hall connections
            
            #every other column is as well.

        #adjust entries by index, for halls/connections
        grid[Y][X] = "O"

print(f"{'#' * 206}")
for line in grid:
    string = " "
    for item in line:
        string+= item
    print("#" + string + "#")
print(f"{'#' * 206}")

print(f"height of grid = {len(grid)}\nwidth of grid = {len(grid[0])}")

        